import '@/styles/globals.css'
import '@mantine/core/styles.css'

import { ColorSchemeScript } from '@mantine/core'
import { Inter as FontSans } from 'next/font/google'
import type { Metadata, Viewport } from 'next'
import { cn } from '@/lib/utils'
import { Toaster } from '@/components/ui/sonner'
import { Providers } from '@/components/providers'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const viewport: Viewport = {
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: 'white' },
    { media: '(prefers-color-scheme: dark)', color: 'black' },
  ],
}

interface RootLayoutProps {
  children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <>
      <html lang='en' suppressHydrationWarning>
        <head>
          <ColorSchemeScript />
        </head>
        <body
          className={cn(
            'min-h-screen font-sans antialiased',
            fontSans.variable
          )}
        >
          <Providers>
            {children}
            <Toaster />
          </Providers>
        </body>
      </html>
    </>
  )
}
